const vocabularyList_verbs = [
  ["aimer", "to love"],
  ["aller", "to go"],
  ["arriver", "to arrive"],
  ["avoir", "to have"],
  ["apprendre", "to learn"],
  ["acheter", "to buy"],
  ["attendre", "to wait"],
  ["adapter", "to adapt"],
  ["analyser", "to analyze"],
  ["accueillir", "to welcome"],
  ["agir", "to act"],
  ["admettre", "to admit"],
  ["adopter", "to adopt"],
  ["applaudir", "to applaud"],
  ["abandonner", "to abandon"],
  ["aboyer", "to bark"],
  ["assembler", "to assemble"],
  ["abaisser", "to lower"],
  ["augmenter", "to increase"],
  ["attirer", "to attract"],
  ["accélérer", "to accelerate"],
  ["arrêter", "to stop"],
  ["annoncer", "to announce"],
  ["assister", "to assist"],
  ["appliquer", "to apply"],
  ["avancer", "to advance"],
  ["associer", "to associate"],
  ["apprécier", "to appreciate"],
  ["approcher", "to approach"],
  ["arranger", "to arrange"],
  ["ajouter", "to add"],
  ["abattre", "to knock down"],
  ["apparaître", "to appear"],
  ["améliorer", "to improve"],
  ["adresser", "to address"],
  ["affirmer", "to affirm"],
  ["adorer", "to adore"],
  ["affecter", "to affect"],
  ["autoriser", "to authorize"],
  ["avouer", "to admit"],
  ["animer", "to animate"],
  ["arbitrer", "to arbitrate"],
  ["assurer", "to ensure"],
  ["affronter", "to confront"],
  ["ancrer", "to anchor"],
  ["assigner", "to assign"],
  ["abdiquer", "to abdicate"],
  ["abolir", "to abolish"],
  ["absorber", "to absorb"],
  ["abuser", "to abuse"],
  ["accaparer", "to monopolize"],
  ["acclimater", "to acclimatize"],
  ["accorder", "to grant"],
  ["accuser", "to accuse"],
  ["aduler", "to flatter excessively"],
  ["agacer", "to irritate"],
  ["agrandir", "to enlarge"],
  ["agréer", "to approve"],
  ["aigrir", "to sour"],
  ["ajuster", "to adjust"],
  ["aligner", "to align"],
  ["alourdir", "to make heavier"],
  ["amarrer", "to anchor"],
  ["aménager", "to arrange, to develop"],
  ["apaiser", "to calm"],
  ["arrondir", "to round"],
  ["assainir", "to sanitize"],
  ["assécher", "to dry out"],
  ["assumer", "to assume"],
  ["attacher", "to attach"],
  ["attaquer", "to attack"],
  ["avertir", "to warn"],
  ["assimiler", "to assimilate"],
  ["affiner", "to refine"],
  ["accroître", "to increase"],
  ["aggraver", "to worsen"],
  ["atteindre", "to reach"],
  ["agrémenter", "to embellish"],
  ["bâcher", "to cover (with a tarpaulin)"],
  ["battre", "to beat"],
  ["bénir", "to bless"],
  ["blesser", "to injure"],
  ["boire", "to drink"],
  ["briller", "to shine"],
  ["broder", "to embroider"],
  ["brouiller", "to confuse"],
  ["briser", "to break"],
  ["balancer", "to balance, to swing"],
  ["bousculer", "to jostle, to push"],
  ["bousiller", "to wreck, to ruin"],
  ["bâiller", "to yawn"],
  ["blanchir", "to whiten, to bleach"],
  ["blâmer", "to blame"],
  ["barguigner", "to haggle"],
  ["barrer", "to block, to bar"],
  ["bavarder", "to chat"],
  ["boiter", "to limp"],
  ["brûler", "to burn"],
  ["balayer", "to sweep"],
  ["bousculer", "to shove, to push"],
  ["bavarder", "to chat"],
  ["blâmer", "to blame"],
  ["briser", "to break"],
  ["bouder", "to sulk"],
  ["barbouiller", "to smear"],
  ["bâtir", "to build"],
  ["bouger", "to move"],
  ["buter", "to stumble, to kick"],
  ["bégayer", "to stutter"],
  ["bander", "to bandage"],
  ["brouter", "to browse (eating grass)"],
  ["cacher", "to hide"],
  ["changer", "to change"],
  ["chercher", "to search, to look for"],
  ["comprendre", "to understand"],
  ["commencer", "to begin"],
  ["construire", "to build"],
  ["connaître", "to know (someone)"],
  ["couper", "to cut"],
  ["conseiller", "to advise"],
  ["cuisiner", "to cook"],
  ["créer", "to create"],
  ["contacter", "to contact"],
  ["croire", "to believe"],
  ["comparer", "to compare"],
  ["corriger", "to correct"],
  ["chasser", "to hunt"],
  ["cligner", "to blink"],
  ["chanter", "to sing"],
  ["calculer", "to calculate"],
  ["courir", "to run"],
  ["conquérir", "to conquer"],
  ["crier", "to shout"],
  ["combiner", "to combine"],
  ["croître", "to grow (plants)"],
  ["clore", "to close"],
  ["copier", "to copy"],
  ["coller", "to stick, to paste"],
  ["choisir", "to choose"],
  ["casser", "to break"],
  ["céder", "to yield"],
  ["convaincre", "to convince"],
  ["chiffonner", "to crumple"],
  ["claquer", "to slam, to clap"],
  ["chuter", "to fall"],
  ["compter", "to count"],
  ["convier", "to invite"],
  ["couler", "to flow"],
  ["climater", "to climatize"],
  ["compenser", "to compensate"],
  ["citer", "to cite"],
  ["chauffer", "to heat"],
  ["chatouiller", "to tickle"],
  ["chiffrer", "to calculate, to cipher"],
  ["chouiner", "to whine"],
  ["chauler", "to walk on stilts"],
  ["chérir", "to cherish"],
  ["choquer", "to shock"],
  ["chouffer", "to smoke (cigarettes)"],
  ["chagriner", "to grieve"],
  ["chiffonner", "to wrinkle"],
  ["chiner", "to bargain"],
  ["changer", "to change"],
  ["chasser", "to hunt"],
  ["décider", "to decide"],
  ["demander", "to ask"],
  ["donner", "to give"],
  ["dormir", "to sleep"],
  ["devoir", "to have to, must"],
  ["dire", "to say"],
  ["détruire", "to destroy"],
  ["décrire", "to describe"],
  ["devenir", "to become"],
  ["découvrir", "to discover"],
  ["douter", "to doubt"],
  ["danser", "to dance"],
  ["détester", "to hate"],
  ["diriger", "to direct"],
  ["désirer", "to desire"],
  ["définir", "to define"],
  ["distribuer", "to distribute"],
  ["développer", "to develop"],
  ["déjeuner", "to have lunch"],
  ["démander", "to request"],
  ["dépenser", "to spend (money)"],
  ["démolir", "to demolish"],
  ["déranger", "to disturb"],
  ["déjouer", "to thwart"],
  ["discuter", "to discuss"],
  ["délivrer", "to deliver"],
  ["divorcer", "to divorce"],
  ["dériver", "to drift"],
  ["débattre", "to debate"],
  ["démarrer", "to start, to begin"],
  ["défendre", "to defend"],
  ["déguster", "to taste, to savor"],
  ["déformer", "to deform"],
  ["détendre", "to relax"],
  ["dénoncer", "to denounce"],
  ["divertir", "to entertain"],
  ["distinguer", "to distinguish"],
  ["déroger", "to deviate"],
  ["délirer", "to rave, to hallucinate"],
  ["dévorer", "to devour"],
  ["écouter", "to listen"],
  ["écrire", "to write"],
  ["être", "to be"],
  ["enlever", "to remove"],
  ["entrer", "to enter"],
  ["étudier", "to study"],
  ["expliquer", "to explain"],
  ["épouser", "to marry"],
  ["envoyer", "to send"],
  ["essayer", "to try"],
  ["économiser", "to save (money)"],
  ["exister", "to exist"],
  ["éclairer", "to light up"],
  ["établir", "to establish"],
  ["élever", "to raise"],
  ["empêcher", "to prevent"],
  ["étonner", "to surprise"],
  ["embêter", "to annoy"],
  ["emprunter", "to borrow"],
  ["envier", "to envy"],
  ["encourager", "to encourage"],
  ["exprimer", "to express"],
  ["exercer", "to exercise (a profession)"],
  ["écarter", "to remove, to set aside"],
  ["échapper", "to escape"],
  ["éclater", "to explode"],
  ["évaluer", "to evaluate"],
  ["employer", "to employ"],
  ["enrichir", "to enrich"],
  ["envisager", "to envisage"],
  ["élargir", "to widen"],
  ["exclure", "to exclude"],
  ["étendre", "to extend"],
  ["examiner", "to examine"],
  ["exiger", "to demand"],
  ["élire", "to elect"],
  ["énerver", "to annoy, to irritate"],
  ["exhiber", "to exhibit"],
  ["essouffler", "to be out of breath"],
  ["effacer", "to erase"],
  ["exploiter", "to exploit"],
  ["équilibrer", "to balance"],
  ["embellir", "to embellish"],
  ["épanouir", "to blossom, to flourish"],
  ["embaucher", "to hire"],
  ["évoluer", "to evolve"],
  ["examiner", "to inspect"],
  ["élargir", "to enlarge"],
  ["faire", "to do, to make"],
  ["falloir", "to be necessary"],
  ["fuir", "to flee"],
  ["finir", "to finish"],
  ["fêter", "to celebrate"],
  ["fondre", "to melt"],
  ["forcer", "to force"],
  ["franchir", "to cross, to overcome"],
  ["flotter", "to float"],
  ["fabriquer", "to manufacture"],
  ["fonctionner", "to function"],
  ["flatter", "to flatter"],
  ["frimer", "to show off"],
  ["fixer", "to fix"],
  ["figurer", "to figure, to appear"],
  ["fouiller", "to search, to rummage"],
  ["fasciner", "to fascinate"],
  ["fréquenter", "to frequent"],
  ["fusiller", "to shoot (with a gun)"],
  ["fermer", "to close, to shut"],
  ["fumer", "to smoke"],
  ["fléchir", "to bend, to sway"],
  ["fournir", "to supply, to provide"],
  ["fustiger", "to berate, to criticize severely"],
  ["feindre", "to feign, to pretend"],
  ["fouetter", "to whip"],
  ["foutre", "to put, to throw (informal)"],
  ["faillir", "to fail, to almost"],
  ["fouiller", "to rummage, to search thoroughly"],
  ["garder", "to keep, to guard"],
  ["goûter", "to taste"],
  ["grandir", "to grow up"],
  ["glisser", "to slip"],
  ["grimper", "to climb"],
  ["gronder", "to scold"],
  ["guérir", "to heal"],
  ["geler", "to freeze"],
  ["générer", "to generate"],
  ["gratter", "to scratch"],
  ["galérer", "to struggle, to have a hard time"],
  ["garer", "to park (a car)"],
  ["grouiller", "to swarm, to move around"],
  ["gémir", "to moan"],
  ["gérer", "to manage"],
  ["gratifier", "to gratify"],
  ["griller", "to grill"],
  ["généraliser", "to generalize"],
  ["guider", "to guide"],
  ["gloser", "to gossip"],
  ["gonfler", "to inflate"],
  ["générer", "to generate"],
  ["gagner", "to win, to earn"],
  ["habiller", "to dress"],
  ["hésiter", "to hesitate"],
  ["hurler", "to scream"],
  ["hommager", "to honor"],
  ["humer", "to smell"],
  ["hiberner", "to hibernate"],
  ["héberger", "to host, to accommodate"],
  ["happer", "to snap, to grab"],
  ["harnacher", "to harness"],
  ["haleter", "to pant"],
  ["hériter", "to inherit"],
  ["hurler", "to howl, to scream"],
  ["houspiller", "to scold"],
  ["harmoniser", "to harmonize"],
  ["halluciner", "to hallucinate"],
  ["hacher", "to chop"],
  ["huer", "to boo, to shout at"],
  ["hisser", "to hoist"],
  ["heurter", "to hit, to collide with"],
  ["harceler", "to harass"],
  ["haleter", "to pant"],
  ["héler", "to hail (a taxi, for example)"],
  ["hurler", "to yell, to scream"],
  ["habiter", "to live in"],
  ["halluciner", "to hallucinate"],
  ["humer", "to sniff, to smell"],
  ["hésiter", "to hesitate"],
  ["habiter", "to live, to dwell"],
  ["harmoniser", "to harmonize"],
  ["hiberner", "to hibernate"],
  ["humer", "to smell, to inhale"],
  ["hacher", "to chop"],
  ["huer", "to boo, to shout at"],
  ["hisser", "to hoist"],
  ["heurter", "to hit, to collide with"],
  ["hésiter", "to hesitate"],
  ["humer", "to inhale, to smell"],
  ["harceler", "to harass"],
  ["haleter", "to pant"],
  ["héler", "to hail (a taxi, for example)"],
  ["hurler", "to yell, to scream"],
  ["habiter", "to live in"],
  ["habiller", "to dress"],
  ["humer", "to sniff, to inhale"],
  ["hiberner", "to hibernate"],
  ["happer", "to grab"],
  ["houspiller", "to scold"],
  ["harmoniser", "to make harmonious"],
  ["hérisser", "to bristle"],
  ["humer", "to smell"],
  ["haleter", "to pant"],
  ["hurler", "to shout"],
  ["habiller", "to clothe, to dress"],
  ["harnacher", "to harness"],
  ["hurler", "to howl"],
  ["hommager", "to pay tribute"],
  ["haleter", "to pant"],
  ["imaginer", "to imagine"],
  ["ignorer", "to ignore"],
  ["informer", "to inform"],
  ["installer", "to install"],
  ["identifier", "to identify"],
  ["introduire", "to introduce"],
  ["interdire", "to forbid"],
  ["inspirer", "to inspire"],
  ["inviter", "to invite"],
  ["imiter", "to imitate"],
  ["instruire", "to instruct"],
  ["inciter", "to incite"],
  ["interroger", "to question"],
  ["interpréter", "to interpret"],
  ["innover", "to innovate"],
  ["intervenir", "to intervene"],
  ["influencer", "to influence"],
  ["insister", "to insist"],
  ["installer", "to set up"],
  ["implorer", "to implore"],
  ["intégrer", "to integrate"],
  ["intéresser", "to interest"],
  ["informer", "to inform"],
  ["influencer", "to influence"],
  ["intercepter", "to intercept"],
  ["immigrer", "to immigrate"],
  ["identifier", "to identify"],
  ["incarner", "to embody"],
  ["installer", "to settle, to install"],
  ["impliquer", "to implicate"],
  ["illustrer", "to illustrate"],
  ["incorporer", "to incorporate"],
  ["investir", "to invest"],
  ["inventer", "to invent"],
  ["intimider", "to intimidate"],
  ["interrompre", "to interrupt"],
  ["ignorer", "to not know, to ignore"],
  ["illustrer", "to illustrate"],
  ["importer", "to import"],
  ["ignorer", "to be unaware of"],
  ["imiter", "to imitate"],
  ["installer", "to arrange"],
  ["inculper", "to accuse"],
  ["inaugurer", "to inaugurate"],
  ["intensifier", "to intensify"],
  ["impliquer", "to involve"],
  ["inviter", "to invite"],
  ["implorer", "to beg, to implore"],
  ["jouer", "to play"],
  ["jeter", "to throw"],
  ["jouir", "to enjoy"],
  ["jurer", "to swear"],
  ["joindre", "to join"],
  ["juger", "to judge"],
  ["jaunir", "to turn yellow"],
  ["jauger", "to estimate"],
    ["kiffer", "to like, to enjoy (slang)"],
  ["lire", "to read"],
  ["laver", "to wash"],
  ["lever", "to raise, to lift"],
  ["louer", "to rent, to hire"],
  ["lancer", "to throw, to launch"],
  ["laisser", "to leave, to let"],
  ["lutter", "to struggle, to fight"],
  ["léguer", "to bequeath"],
  ["lisser", "to smooth"],
  ["loucher", "to squint"],
  ["limer", "to file (shaping something)"],
  ["limiter", "to limit"],
  ["lourder", "to unload, to drop (slang)"],
  ["ligoter", "to tie up, to bind"],
  ["languir", "to languish, to suffer"],
  ["lacer", "to lace, to tie (shoes)"],
  ["manger", "to eat"],
  ["marcher", "to walk"],
  ["mettre", "to put, to place"],
  ["maintenir", "to maintain"],
  ["mourir", "to die"],
  ["mentir", "to lie"],
  ["montrer", "to show"],
  ["mélanger", "to mix"],
  ["mener", "to lead"],
  ["manquer", "to miss"],
  ["migrer", "to migrate"],
  ["marier", "to marry"],
  ["maigrir", "to lose weight"],
  ["marquer", "to mark, to brand"],
  ["mériter", "to deserve"],
  ["mordre", "to bite"],
  ["moduler", "to modulate"],
  ["moucher", "to blow one's nose"],
  ["murmurer", "to murmur"],
  ["mouiller", "to wet"],
  ["moudre", "to grind"],
  ["mépriser", "to despise"],
  ["mesurer", "to measure"],
  ["manier", "to handle, to manage"],
  ["marchander", "to haggle"],
  ["maîtriser", "to master, to control"],
  ["mimer", "to mime"],
  ["mémoriser", "to memorize"],
  ["nager", "to swim"],
  ["naître", "to be born"],
  ["négocier", "to negotiate"],
  ["noter", "to note"],
  ["nourrir", "to feed"],
  ["nettoyer", "to clean"],
  ["noyer", "to drown"],
  ["négliger", "to neglect"],
  ["nommer", "to name"],
  ["nuire", "to harm"],
  ["naviguer", "to navigate"],
  ["nouer", "to tie, to knot"],
  ["nerver", "to annoy, to nerve"],
  ["notifier", "to notify"],
  ["narrer", "to narrate, to tell"],
  ["nicher", "to nest"],
  ["observer", "to observe"],
  ["ouvrir", "to open"],
  ["offrir", "to offer"],
  ["obtenir", "to obtain"],
  ["obéir", "to obey"],
  ["ôter", "to remove"],
  ["opérer", "to operate"],
  ["organiser", "to organize"],
  ["oser", "to dare"],
  ["ombrager", "to shade"],
  ["oublier", "to forget"],
  ["orienter", "to orient, to guide"],
  ["officialiser", "to officialize"],
  ["obscurcir", "to obscure"],
  ["ordonner", "to order"],
  ["occuper", "to occupy"],
  ["offenser", "to offend"],
  ["opposer", "to oppose"],
  ["obliger", "to oblige"],
  ["obséder", "to obsess"],
  ["parler", "to speak"],
  ["partir", "to leave"],
  ["penser", "to think"],
  ["poser", "to put, to place"],
  ["prendre", "to take"],
  ["perdre", "to lose"],
  ["prouver", "to prove"],
  ["pouvoir", "to be able to"],
  ["produire", "to produce"],
  ["préparer", "to prepare"],
  ["prévoir", "to foresee"],
  ["plaire", "to please"],
  ["payer", "to pay"],
  ["promettre", "to promise"],
  ["parvenir", "to reach"],
  ["permettre", "to allow"],
  ["plonger", "to dive"],
  ["prier", "to pray"],
  ["protéger", "to protect"],
  ["participer", "to participate"],
  ["préférer", "to prefer"],
  ["pousser", "to push"],
  ["projeter", "to project"],
  ["partager", "to share"],
  ["progresser", "to progress"],
  ["presser", "to press"],
  ["passer", "to pass"],
  ["parier", "to bet"],
  ["pénétrer", "to penetrate"],
  ["parcourir", "to travel across"],
  ["peindre", "to paint"],
  ["porter", "to carry"],
  ["promener", "to take for a walk"],
  ["proposer", "to propose"],
  ["présenter", "to present"],
  ["prêcher", "to preach"],
  ["planter", "to plant"],
  ["pêcher", "to fish"],
  ["punir", "to punish"],
  ["quitter", "to leave"],
  ["questionner", "to question"],
  ["quoter", "to quote"],
  ["quêter", "to quest, to search for"],
  ["qualifier", "to qualify"],
  ["quiver", "to shake, to quiver"],
  ["quadriller", "to grid, to partition"],
  ["quiller", "to drag (slang)"],
  ["quêter", "to beg, to ask for"],
  ["quoter", "to price (to give a quote)"],
  ["qualifier", "to characterize, to describe"],
  ["quêter", "to search for or seek"],
  ["quêter", "to inquire or to investigate (informal)"],
  ["quitter", "to quit, to leave"],
  ["quêter", "to seek (as in treasure hunting)"],
  ["qualifier", "to define or designate"],
  ["quêter", "to collect donations"],
  ["quitter", "to abandon, to leave behind"],
  ["qualifier", "to rate or assess"],
  ["quiller", "to drag or pull (informal)"],
  ["quoter", "to make an estimate or quote"],
  ["quêter", "to search thoroughly"],
  ["quitter", "to abandon, to leave behind"],
  ["quêter", "to beg for money"],
  ["qualifier", "to describe or label"],
  ["quêter", "to solicit or request"],
  ["qualifier", "to make an assessment or categorization"],
  ["quitter", "to leave, to abandon"],
  ["quêter", "to explore or search for"],
  ["quêter", "to go after something (informal)"],
  ["qualifier", "to categorize or classify"],
  ["quitter", "to vacate, to depart"],
  ["quêter", "to look for, to pursue"],
  ["quitter", "to leave behind"],
  ["quêter", "to gather or search for something"],
  ["qualifier", "to name or label"],
  ["quitter", "to exit or leave a location"],
  ["quêter", "to ask for alms or charity"],
  ["quêter", "to go in search of (informal)"],
  ["qualifier", "to explain or define"],
  ["quêter", "to investigate thoroughly"],
  ["rire", "to laugh"],
  ["regarder", "to look at, to watch"],
  ["répondre", "to answer, to respond"],
  ["réfléchir", "to reflect, to think"],
  ["rentrer", "to go back, to return"],
  ["rester", "to stay, to remain"],
  ["revenir", "to come back, to return"],
  ["remarquer", "to notice"],
  ["recevoir", "to receive"],
  ["remercier", "to thank"],
  ["rassembler", "to gather, to assemble"],
  ["rappeler", "to remind, to call back"],
  ["réussir", "to succeed"],
  ["réaliser", "to realize, to achieve"],
  ["raconter", "to tell (a story)"],
  ["réparer", "to repair"],
  ["rejoindre", "to join, to reunite"],
  ["répéter", "to repeat"],
  ["rompre", "to break up, to rupture"],
  ["régler", "to regulate, to settle (a matter)"],
  ["relever", "to lift, to raise"],
  ["répandre", "to spread, to scatter"],
  ["retirer", "to withdraw, to take out"],
  ["reprocher", "to reproach, to blame"],
  ["reconnaître", "to recognize"],
  ["résister", "to resist"],
  ["reposer", "to rest"],
  ["rouler", "to roll, to drive"],
  ["rattraper", "to catch up, to retrieve"],
  ["régner", "to reign"],
  ["reconquérir", "to reconquer"],
  ["rencontrer", "to meet"],
  ["réagir", "to react"],
  ["relier", "to link, to bind"],
  ["refuser", "to refuse"],
  ["racheter", "to buy back"],
  ["restituer", "to restore"],
  ["remplacer", "to replace"],
  ["remplir", "to fill"],
  ["réduire", "to reduce"],
  ["résoudre", "to resolve"],
  ["remettre", "to put back, to hand over"],
  ["savoir", "to know"],
  ["savoir-faire", "to know how to do"],
  ["sourire", "to smile"],
  ["sortir", "to go out, to exit"],
  ["suivre", "to follow"],
  ["sembler", "to seem"],
  ["sentir", "to feel, to smell"],
  ["se réveiller", "to wake up"],
  ["se laver", "to wash oneself"],
  ["se dépêcher", "to hurry"],
  ["se coucher", "to go to bed"],
  ["se lever", "to get up"],
  ["se souvenir", "to remember"],
  ["s'arrêter", "to stop"],
  ["se fâcher", "to get angry"],
  ["s'endormir", "to fall asleep"],
  ["se taire", "to be silent"],
  ["s'installer", "to settle down"],
  ["s'ennuyer", "to get bored"],
  ["se détendre", "to relax"],
  ["se promener", "to take a walk"],
  ["se battre", "to fight"],
  ["se concentrer", "to concentrate"],
  ["s'habiller", "to get dressed"],
  ["séparer", "to separate"],
  ["succomber", "to succumb"],
  ["saluer", "to greet"],
  ["signer", "to sign"],
  ["sauter", "to jump"],
  ["saisir", "to seize"],
  ["subir", "to undergo"],
  ["suggérer", "to suggest"],
  ["simplifier", "to simplify"],
  ["soutenir", "to support"],
  ["servir", "to serve"],
  ["secouer", "to shake"],
  ["soigner", "to take care of, to treat"],
  ["se présenter", "to introduce oneself"],
  ["s'occuper", "to take care of"],
  ["se défendre", "to defend oneself"],
  ["salir", "to dirty"],
  ["s'inscrire", "to register"],
  ["trouver", "to find"],
  ["travailler", "to work"],
  ["tenir", "to hold"],
  ["téléphoner", "to phone, to call"],
  ["tomber", "to fall"],
  ["tenter", "to attempt"],
  ["tourner", "to turn"],
  ["toucher", "to touch"],
  ["traverser", "to cross"],
  ["tout", "to all, to do everything"],
  ["taire", "to silence, to keep quiet"],
  ["tracer", "to trace, to draw"],
  ["tendre", "to stretch, to tend"],
  ["terminer", "to finish"],
  ["tirer", "to pull, to shoot"],
  ["trembler", "to tremble"],
  ["tricher", "to cheat"],
  ["tâcher", "to try, to attempt"],
  ["transporter", "to transport"],
  ["trancher", "to slice, to decide"],
  ["troubler", "to disturb, to confuse"],
  ["témoigner", "to testify"],
  ["tarder", "to delay"],
  ["télécharger", "to download"],
  ["tinter", "to ring"],
  ["téléviser", "to televise"],
  ["tordre", "to twist"],
  ["trier", "to sort"],
  ["transformer", "to transform"],
  ["transmettre", "to transmit"],
  ["tancer", "to scold"],
  ["wagonner", "to ride in a wagon"],
  ["woter", "to water (rarely used)"],
  ["whistler", "to whistle"],
  ["xénophober", "to xenophobe (to dislike or be prejudiced against foreigners)"],
  ["zapper", "to skip (usually a channel or something that can be ignored)"],
  ["zébrer", "to stripe (to mark with stripes)"],
  ["zigzaguer", "to zigzag"],
  ["zinner", "to zoom (informal, often used in context of moving quickly)"],
  ["zodiaciser", "to relate to the zodiac"],
  ["zéler", "to zealously support or do something with great enthusiasm"],
  ["zinger", "to make a sharp or witty remark"],
  ["zoner", "to zone out, to get lost in thought"],
  ["zéroter", "to achieve a score of zero (in games or tests)"]
];