const vocabularyList_anatomy = [
    ["corps", "body"],
    ["tête", "head"],
    ["cerveau", "brain"],
    ["visage", "face"],
    ["yeux", "eyes"],
    ["oreilles", "ears"],
    ["nez", "nose"],
    ["bouche", "mouth"],
    ["dents", "teeth"],
    ["langue", "tongue"],
    ["cou", "neck"],
    ["épaule", "shoulder"],
    ["bras", "arm"],
    ["main", "hand"],
    ["doigt", "finger"],
    ["poitrine", "chest"],
    ["cœur", "heart"],
    ["poumons", "lungs"],
    ["estomac", "stomach"],
    ["foie", "liver"],
    ["reins", "kidneys"],
    ["intestins", "intestines"],
    ["os", "bone"],
    ["peau", "skin"],
    ["sang", "blood"],
    ["muscle", "muscle"],
    ["genou", "knee"],
    ["jambe", "leg"],
    ["pied", "foot"],
    ["orteil", "toe"],
    ["colonne vertébrale", "spine"],
    ["nerf", "nerve"],
    ["cellule", "cell"],
    ["ADN", "DNA"],
    ["bactérie", "bacteria"],
    ["virus", "virus"],
    ["globule rouge", "red blood cell"],
    ["globule blanc", "white blood cell"],
    ["plante", "plant"],
    ["organisme", "organism"],
    ["moelle épinière", "spinal cord"],
    ["hormone", "hormone"],
    ["système digestif", "digestive system"],
    ["système nerveux", "nervous system"],
    ["système immunitaire", "immune system"],
    ["système respiratoire", "respiratory system"],
    ["système circulatoire", "circulatory system"],
    ["système musculaire", "muscular system"],
    ["système osseux", "skeletal system"],
    ["métabolisme", "metabolism"],
    ["glande", "gland"],
    ["pancréas", "pancreas"],
    ["rate", "spleen"],
    ["utérus", "uterus"],
    ["ovaire", "ovary"],
    ["testicule", "testicle"],
    ["chromosome", "chromosome"],
    ["protéine", "protein"],
    ["enzyme", "enzyme"],
    ["moelle osseuse", "bone marrow"]
];
