const vocabularyList_fashion = [
    ["vêtement", "clothing"],
    ["robe", "dress"],
    ["pantalon", "pants"],
    ["jean", "jeans"],
    ["chemise", "shirt"],
    ["blouse", "blouse"],
    ["t-shirt", "t-shirt"],
    ["pull", "sweater"],
    ["veste", "jacket"],
    ["manteau", "coat"],
    ["écharpe", "scarf"],
    ["gants", "gloves"],
    ["chaussettes", "socks"],
    ["chaussures", "shoes"],
    ["bottes", "boots"],
    ["sandales", "sandals"],
    ["chapeau", "hat"],
    ["casquette", "cap"],
    ["cravate", "tie"],
    ["ceinture", "belt"],
    ["jupe", "skirt"],
    ["short", "shorts"],
    ["legging", "leggings"],
    ["collants", "tights"],
    ["sous-vêtements", "underwear"],
    ["pyjama", "pajamas"],
    ["maillot de bain", "swimsuit"],
    ["lunettes de soleil", "sunglasses"],
    ["sac à main", "handbag"],
    ["sac à dos", "backpack"],
    ["montre", "watch"],
    ["bracelet", "bracelet"],
    ["collier", "necklace"],
    ["boucles d'oreilles", "earrings"],
    ["parfum", "perfume"],
    ["mode", "fashion"],
    ["tissu", "fabric"],
    ["couture", "sewing"],
    ["défilé de mode", "fashion show"],
    ["styliste", "fashion designer"]
];
