
const vocabularyList_sports = [
    ["sport", "sport"],
    ["athlétisme", "athletics"],
    ["football", "soccer"],
    ["basketball", "basketball"],
    ["handball", "handball"],
    ["rugby", "rugby"],
    ["tennis", "tennis"],
    ["volleyball", "volleyball"],
    ["hockey", "hockey"],
    ["natation", "swimming"],
    ["course", "race"],
    ["vélo", "bicycle"],
    ["ski", "skiing"],
    ["alpinisme", "mountain climbing"],
    ["boxe", "boxing"],
    ["arts martiaux", "martial arts"],
    ["gymnastique", "gymnastics"],
    ["plongée", "diving"],
    ["surf", "surfing"],
    ["canoë", "canoeing"],
    ["kayak", "kayaking"],
    ["ping-pong", "table tennis"],
    ["badminton", "badminton"],
    ["football américain", "American football"],
    ["baseball", "baseball"],
    ["golf", "golf"],
    ["équestre", "equestrian"],
    ["escalade", "climbing"],
    ["lutte", "wrestling"],
    ["tir à l'arc", "archery"],
    ["athlète", "athlete"],
    ["équipe", "team"],
    ["compétition", "competition"],
    ["match", "match"],
    ["champion", "champion"],
    ["gagner", "to win"],
    ["perdre", "to lose"],
    ["entraînement", "training"],
    ["médailles", "medals"],
    ["vainqueur", "winner"],
    ["défaite", "defeat"],
    ["score", "score"],
    ["stade", "stadium"],
    ["arbitre", "referee"],
    ["spectateur", "spectator"],
    ["coach", "coach"],
    ["record", "record"],
    ["saison", "season"]
];
