const vocabularyList_work = [
  ["avocat", "lawyer"],
  ["médecin", "doctor"],
  ["infirmier", "nurse"],
  ["enseignant", "teacher"],
  ["architecte", "architect"],
  ["ingénieur", "engineer"],
  ["dentiste", "dentist"],
  ["pharmacien", "pharmacist"],
  ["comptable", "accountant"],
  ["journaliste", "journalist"],
  ["acteur", "actor"],
  ["actrice", "actress"],
  ["musicien", "musician"],
  ["chanteur", "singer"],
  ["sculpteur", "sculptor"],
  ["peintre", "painter"],
  ["designer", "designer"],
  ["écrivain", "writer"],
  ["chercheur", "researcher"],
  ["programmeur", "programmer"],
  ["développeur", "developer"],
  ["technicien", "technician"],
  ["chef", "chef"],
  ["serveur", "waiter"],
  ["cuisinier", "cook"],
  ["barman", "bartender"],
  ["plombier", "plumber"],
  ["électricien", "electrician"],
  ["maçon", "mason"],
  ["charpentier", "carpenter"],
  ["menuisier", "joiner"],
  ["peintre en bâtiment", "painter (construction)"],
  ["chauffeur", "driver"],
  ["conducteur", "conductor"],
  ["pilote", "pilot"],
  ["hôtesse de l'air", "flight attendant"],
  ["agent de voyage", "travel agent"],
  ["réceptionniste", "receptionist"],
  ["responsable", "manager"],
  ["directeur", "director"],
  ["PDG", "CEO"],
  ["assistant", "assistant"],
  ["secrétaire", "secretary"],
  ["analyste", "analyst"],
  ["conseiller", "consultant"],
  ["avocat", "attorney"],
  ["spécialiste", "specialist"],
  ["coach", "coach"],
  ["éducateur", "educator"],
  ["psychologue", "psychologist"],
  ["psychiatre", "psychiatrist"],
  ["chirurgien", "surgeon"],
  ["médecin généraliste", "general practitioner"],
  ["vétérinaire", "veterinarian"],
  ["éducateur spécialisé", "special needs teacher"],
  ["professeur", "professor"],
  ["surveillant", "supervisor"],
  ["analyste de données", "data analyst"],
  ["technicien en informatique", "IT technician"],
  ["responsable RH", "HR manager"],
  ["commerçant", "merchant"],
  ["vendeur", "salesperson"],
  ["marchand", "trader"],
  ["publicitaire", "advertiser"],
  ["gestionnaire", "administrator"],
  ["directeur des ventes", "sales director"],
  ["directeur financier", "financial director"],
  ["commerçant", "shopkeeper"],
  ["gérant", "manager (store)"],
  ["commerçant en ligne", "online retailer"],
  ["designer graphique", "graphic designer"],
  ["développeur web", "web developer"],
  ["webmaster", "webmaster"],
  ["gestionnaire de projet", "project manager"],
  ["responsable marketing", "marketing manager"],
  ["responsable des communications", "communications manager"],
  ["journaliste d'investigation", "investigative journalist"],
  ["éditeur", "editor"],
  ["rédacteur", "copywriter"],
  ["correcteur", "proofreader"],
  ["éditeur de contenu", "content editor"],
  ["chef de projet", "project leader"],
  ["formateur", "trainer"],
  ["formateur en entreprise", "corporate trainer"],
  ["garde d'enfants", "childcare worker"],
  ["assistant social", "social worker"],
  ["interprète", "interpreter"],
  ["traducteur", "translator"],
  ["ingénieur civil", "civil engineer"],
  ["architecte paysagiste", "landscape architect"],
  ["planificateur", "planner"],
  ["technicien en génie civil", "civil engineering technician"],
  ["responsable sécurité", "safety officer"],
  ["technicien médical", "medical technician"],
  ["préparateur en pharmacie", "pharmacy assistant"],
  ["conducteur de train", "train driver"],
  ["chauffeur de bus", "bus driver"],
  ["électricien industriel", "industrial electrician"],
  ["artisan", "artisan"],
  ["garde du corps", "bodyguard"],
  ["réparateur automobile", "car mechanic"],
  ["technicien informatique", "computer technician"],
  ["gestionnaire de stock", "inventory manager"],
  ["coordinateur d'événements", "event coordinator"],
  ["consultant en gestion", "management consultant"],
  ["comptable fiscaliste", "tax accountant"],
  ["notaire", "notary"],
  ["directeur artistique", "art director"]
];
