const vocabularyList_school = [
    ["école", "school"],
    ["professeur", "teacher"],
    ["élève", "student"],
    ["cours", "class"],
    ["classe", "classroom"],
    ["tableau", "blackboard"],
    ["livre", "book"],
    ["cahier", "notebook"],
    ["stylo", "pen"],
    ["crayon", "pencil"],
    ["gomme", "eraser"],
    ["règle", "ruler"],
    ["cartable", "schoolbag"],
    ["sac à dos", "backpack"],
    ["chaise", "chair"],
    ["bureau", "desk"],
    ["fenêtre", "window"],
    ["porte", "door"],
    ["plancher", "floor"],
    ["plafond", "ceiling"],
    ["horloge", "clock"],
    ["horaires", "schedule"],
    ["récréation", "recess"],
    ["pause", "break"],
    ["devoirs", "homework"],
    ["examen", "exam"],
    ["test", "test"],
    ["question", "question"],
    ["réponse", "answer"],
    ["note", "grade"],
    ["bulletin", "report card"],
    ["diplôme", "diploma"],
    ["éducation", "education"],
    ["savoir", "knowledge"],
    ["apprentissage", "learning"],
    ["écolier", "schoolboy"],
    ["écolière", "schoolgirl"],
    ["baccalauréat", "baccalaureate"],
    ["université", "university"],
    ["faculté", "faculty"],
    ["collège", "middle school"],
    ["lycée", "high school"],
    ["primaire", "primary school"],
    ["enseignant", "educator"],
    ["responsable", "principal"],
    ["bureau du directeur", "principal's office"],
    ["emploi du temps", "timetable"],
    ["salle informatique", "computer room"],
    ["salle des profs", "teachers' room"],
    ["club", "club"]
];
