  const vocabularyList_food = [


 ["ustensile", "utensil"],
    ["couteau", "knife"],
    ["fourchette", "fork"],
    ["cuillère", "spoon"],
    ["assiette", "plate"],
    ["verre", "glass"],
    ["gobelet", "cup"],
    ["tasse", "mug"],
    ["bol", "bowl"],
    ["poêle", "pan"],
    ["casserole", "saucepan"],
    ["marmite", "pot"],
    ["plat", "dish"],
    ["planche à découper", "cutting board"],
    ["râpe", "grater"],
    ["fouet", "whisk"],
    ["mélangeur", "mixer"],
    ["presse-agrumes", "juicer"],
    ["ouvre-bouteille", "bottle opener"],
    ["tire-bouchon", "corkscrew"],
    ["passoire", "strainer"],
    ["éplucheur", "peeler"],
    ["spatule", "spatula"],
    ["cuillère en bois", "wooden spoon"],
    ["louche", "ladle"],
    ["ramequin", "ramekin"],
    ["moule", "mold"],
    ["grille-pain", "toaster"],
    ["micro-ondes", "microwave"],
    ["cafetière", "coffee maker"],
    ["bouilloire", "kettle"],
    ["plaques de cuisson", "stove top"],
    ["couverts", "cutlery"],
    ["panier", "basket"],
    ["torchon", "dishcloth"],
    ["linge de table", "tablecloth"],
    ["nappe", "tablecloth"],
    ["couteau à pain", "bread knife"],
    ["brochette", "skewer"],
    ["pain", "bread"],
    ["fromage", "cheese"],
    ["pomme", "apple"],
    ["vin", "wine"],
    ["eau", "water"],
    ["lait", "milk"],
    ["beurre", "butter"],
    ["sel", "salt"],
    ["poivre", "pepper"],
    ["viande", "meat"],
    ["poisson", "fish"],
    ["poulet", "chicken"],
    ["boeuf", "beef"],
    ["jambon", "ham"],
    ["sucre", "sugar"],
    ["huile", "oil"],
    ["farine", "flour"],
    ["légumes", "vegetables"],
    ["carotte", "carrot"],
    ["tomate", "tomato"],
    ["oignon", "onion"],
    ["ail", "garlic"],
    ["salade", "salad"],
    ["œuf", "egg"],
    ["riz", "rice"],
    ["pâtes", "pasta"],
    ["gâteau", "cake"],
    ["chocolat", "chocolate"],
    ["glace", "ice cream"],
    ["miel", "honey"],
    ["lard", "bacon"],
    ["bouillon", "broth"],
    ["pistache", "pistachio"],
    ["haricot", "bean"],
    ["lentille", "lentil"],
    ["orge", "barley"],
    ["avoine", "oat"],
    ["seigle", "rye"],
    ["figue", "fig"],
    ["datte", "date (fruit)"],
    ["cassis", "blackcurrant"],
    ["groseille", "redcurrant"],
    ["ciboulette", "chives"],
    ["persil", "parsley"],
    ["estragon", "tarragon"],
    ["romarin", "rosemary"],
    ["thym", "thyme"],
    ["basilic", "basil"],
    ["safran", "saffron"],
    ["cannelle", "cinnamon"],
    ["vanille", "vanilla"],
    ["gingembre", "ginger"],
    ["clou de girofle", "clove"],
    ["noix de muscade", "nutmeg"],
    ["cardamome", "cardamom"],
    ["anis", "anise"],
    ["piment", "chili pepper"],
    ["poivron", "bell pepper"],
    ["fenouil", "fennel"],
    ["coriandre", "coriander"],
    ["menthe", "mint"],
    ["laurier", "bay leaf"],
    ["réglisse", "licorice"],
    ["prune", "plum"],
    ["abricot", "apricot"],
    ["coing", "quince"],
    ["grenade", "pomegranate"],
    ["châtaigne", "chestnut"],
    ["noix de coco", "coconut"],
    ["raisin", "grape"],
    ["figue sèche", "dried fig"],
    ["abricot sec", "dried apricot"],
    ["raisins secs", "raisins"],
    ["dattes sèches", "dried dates"],
    ["amarante", "amaranth"],
    ["quinoa", "quinoa"],
    ["épeautre", "spelt"],
    ["sésame", "sesame"],
    ["tournesol", "sunflower seed"],
    ["courge", "pumpkin"],
    ["potiron", "butternut squash"],
    ["gombo", "okra"],
    ["chou frisé", "kale"],
    ["topinambour", "Jerusalem artichoke"],
    ["raifort", "horseradish"],
    ["estragon", "tarragon"],
    ["curcuma", "turmeric"],
    ["cresson", "watercress"],
    ["navet", "turnip"],
    ["radis", "radish"],
    ["ratatouille", "ratatouille"],
    ["bouillabaisse", "fish stew"],
    ["cassoulet", "bean and meat stew"],
    ["coq au vin", "chicken in wine"],
    ["boeuf bourguignon", "beef stew with red wine"],
    ["tarte tatin", "upside-down caramelized apple tart"],
    ["quiche lorraine", "savory pie with eggs and bacon"],
    ["choucroute garnie", "Alsatian sauerkraut with sausages"],
    ["gratin dauphinois", "potato gratin"],
    ["pissaladière", "onion and anchovy tart"],
    ["pot-au-feu", "French beef stew"],
    ["salade niçoise", "Nice-style salad"],
    ["soupe à l'oignon", "French onion soup"],
    ["canard à l'orange", "duck with orange sauce"],
    ["foie gras", "duck or goose liver"],
    ["escargots de Bourgogne", "Burgundy snails"],
    ["galette des rois", "king cake"],
    ["moules marinières", "mussels in white wine sauce"],
    ["tartiflette", "potato, bacon, and cheese dish"],
    ["clafoutis", "cherry baked dessert"],
    ["cuisine", "kitchen"],
    ["four", "oven"],
    ["cuisinière", "stove"],
    ["frigo", "fridge"],
    ["congélateur", "freezer"],
    ["évier", "sink"],
    ["lave-vaisselle", "dishwasher"],
    ["micro-ondes", "microwave"],
    ["plaque de cuisson", "cooktop"],
    ["hotte", "range hood"],
    ["mixeur", "blender"],
    ["couteau", "knife"],
    ["fourchette", "fork"],
    ["cuillère", "spoon"],
    ["assiette", "plate"],
    ["verre", "glass"],
    ["tasse", "cup"],
    ["bol", "bowl"],
    ["nappe", "tablecloth"],
    ["serviette", "napkin"],
    ["menu", "menu"],
    ["serveur", "waiter"],
    ["serveuse", "waitress"],
    ["chef", "chef"],
    ["cuisinier", "cook"],
    ["maître d'hôtel", "head waiter"],
    ["addition", "bill/check"],
    ["pourboire", "tip"],
    ["réservation", "reservation"],
    ["table", "table"],
    ["commande", "order"],
    ["entrée", "appetizer"],
    ["plat principal", "main course"],
    ["dessert", "dessert"],
    ["boisson", "drink"],
    ["vin", "wine"],
    ["bière", "beer"],
    ["café", "coffee"],
    ["thé", "tea"]
];
