const vocabularyList_history = [
    ["histoire", "history"],
    ["préhistoire", "prehistory"],
    ["antiquité", "antiquity"],
    ["Moyen Âge", "Middle Ages"],
    ["Renaissance", "Renaissance"],
    ["Révolution", "Revolution"],
    ["Empire", "Empire"],
    ["colonisation", "colonization"],
    ["indépendance", "independence"],
    ["monarchie", "monarchy"],
    ["république", "republic"],
    ["démocratie", "democracy"],
    ["dictature", "dictatorship"],
    ["féodalité", "feudalism"],
    ["guerre", "war"],
    ["bataille", "battle"],
    ["armée", "army"],
    ["soldat", "soldier"],
    ["chevalier", "knight"],
    ["empereur", "emperor"],
    ["roi", "king"],
    ["reine", "queen"],
    ["président", "president"],
    ["révolution industrielle", "industrial revolution"],
    ["première guerre mondiale", "World War I"],
    ["seconde guerre mondiale", "World War II"],
    ["guerre froide", "Cold War"],
    ["château", "castle"],
    ["citadelle", "citadel"],
    ["forteresse", "fortress"],
    ["traité", "treaty"],
    ["accord", "agreement"],
    ["constitution", "constitution"],
    ["droits de l'homme", "human rights"],
    ["abolition", "abolition"],
    ["esclavage", "slavery"],
    ["conquête", "conquest"],
    ["révolte", "uprising"],
    ["civilisation", "civilization"],
    ["époque", "era"],
    ["dynastie", "dynasty"],
    ["héritage", "heritage"],
    ["archéologie", "archaeology"],
    ["document historique", "historical document"],
    ["manuscrit", "manuscript"],
    ["chronologie", "chronology"],
    ["biographie", "biography"],
    ["témoignage", "testimony"],
    ["musée", "museum"],
    ["monument", "monument"],
    ["vestige", "ruin"],
    ["empire romain", "Roman Empire"],
    ["révolution française", "French Revolution"],
    ["Napoléon Bonaparte", "Napoleon Bonaparte"],
    ["guerre civile", "civil war"],
    ["déclaration d'indépendance", "declaration of independence"],
    ["dictateur", "dictator"],
    ["peuple", "people"],
    ["souveraineté", "sovereignty"]
];
