const vocabularyList_city = [
    ["ville", "city"],
    ["rue", "street"],
    ["avenue", "avenue"],
    ["boulevard", "boulevard"],
    ["trottoir", "sidewalk"],
    ["carrefour", "intersection"],
    ["feux de signalisation", "traffic lights"],
    ["passage piéton", "pedestrian crossing"],
    ["rond-point", "roundabout"],
    ["parking", "parking lot"],
    ["centre-ville", "downtown"],
    ["banlieue", "suburb"],
    ["immeuble", "building"],
    ["gratte-ciel", "skyscraper"],
    ["parc", "park"],
    ["jardin public", "public garden"],
    ["banc", "bench"],
    ["fontaine", "fountain"],
    ["statue", "statue"],
    ["pont", "bridge"],
    ["rivière", "river"],
    ["gare", "train station"],
    ["métro", "subway"],
    ["arrêt de bus", "bus stop"],
    ["aéroport", "airport"],
    ["hôtel de ville", "town hall"],
    ["église", "church"],
    ["cathédrale", "cathedral"],
    ["mosquée", "mosque"],
    ["synagogue", "synagogue"],
    ["hôpital", "hospital"],
    ["pharmacie", "pharmacy"],
    ["police", "police station"],
    ["pompiers", "fire station"],
    ["marché", "market"],
    ["supermarché", "supermarket"],
    ["magasin", "shop"],
    ["centre commercial", "shopping mall"],
    ["cinéma", "movie theater"],
    ["théâtre", "theater"],
    ["musée", "museum"],
    ["bibliothèque", "library"],
    ["université", "university"],
    ["école", "school"],
    ["zoo", "zoo"],
    ["stade", "stadium"],
    ["parking souterrain", "underground parking"],
    ["piste cyclable", "bike lane"],
    ["autoroute", "highway"],
    ["périphérique", "ring road"],
    ["embouteillage", "traffic jam"],
    ["tunnel", "tunnel"],
    ["port", "harbor"],
    ["gare routière", "bus station"],
    ["station-service", "gas station"],
    ["panneau de signalisation", "road sign"],
    ["station de taxis", "taxi stand"],
    ["caserne", "barracks"],
    ["monument", "monument"],
    ["office du tourisme", "tourist office"],
];

