const vocabularyList_emotions = [
    ["psychologie", "psychology"],
    ["esprit", "mind"],
    ["cerveau", "brain"],
    ["comportement", "behavior"],
    ["émotion", "emotion"],
    ["sentiment", "feeling"],
    ["pensée", "thought"],
    ["raisonnement", "reasoning"],
    ["perception", "perception"],
    ["cognition", "cognition"],
    ["conscience", "consciousness"],
    ["subconscient", "subconscious"],
    ["mémoire", "memory"],
    ["apprentissage", "learning"],
    ["motivation", "motivation"],
    ["attention", "attention"],
    ["créativité", "creativity"],
    ["intuition", "intuition"],
    ["intelligence", "intelligence"],
    ["personnalité", "personality"],
    ["identité", "identity"],
    ["estime de soi", "self-esteem"],
    ["confiance en soi", "self-confidence"],
    ["stress", "stress"],
    ["anxiété", "anxiety"],
    ["dépression", "depression"],
    ["tristesse", "sadness"],
    ["colère", "anger"],
    ["peur", "fear"],
    ["joie", "joy"],
    ["bonheur", "happiness"],
    ["frustration", "frustration"],
    ["culpabilité", "guilt"],
    ["honte", "shame"],
    ["amour", "love"],
    ["haine", "hatred"],
    ["jalousie", "jealousy"],
    ["empathie", "empathy"],
    ["sympathie", "sympathy"],
    ["sensation", "sensation"],
    ["hallucination", "hallucination"],
    ["rêve", "dream"],
    ["cauchemar", "nightmare"],
    ["instinct", "instinct"],
    ["habitude", "habit"],
    ["traumatisme", "trauma"],
    ["résilience", "resilience"],
    ["phobie", "phobia"],
    ["trouble mental", "mental disorder"],
    ["psychose", "psychosis"],
    ["schizophrénie", "schizophrenia"],
    ["bipolarité", "bipolar disorder"],
    ["addiction", "addiction"],
    ["hypnose", "hypnosis"],
    ["psychanalyse", "psychoanalysis"],
    ["psychothérapie", "psychotherapy"],
    ["comportementalisme", "behaviorism"],
    ["humanisme", "humanism"],
    ["subconscient collectif", "collective subconscious"],
    ["expérience de mort imminente", "near-death experience"]
];
